apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/myspotontheweb/argocd-workloads-demo.git
      revision: HEAD
      directories:
      - path: apps/*/prod
  template:
    metadata:
      name: '{{path[1]}}-prod'
    spec:
      project: "prod"
      source:
        repoURL: https://github.com/myspotontheweb/argocd-workloads-demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}-prod'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
